# -*- coding: utf-8 -*-
"""Student Risk Dashboard

Goal: Predict graduation probability for enrolled students.

This dashboard loads predictions from `pred_data.csv` (generated by app.py),
filters currently enrolled students, and shows:
- KPI summary (Total students, Graduates, Dropouts, Enrolled)
- Prediction summary for enrolled (Predicted Graduate >50%, Predicted Dropout <50%,
  Average graduation probability with a progress bar)
- Risk distribution (High, Medium, Low) based on Prob_Graduate
- Academic drivers (top features from model: approval_rate_1st, failure_rate_1st,
  approval_rate_2nd, failure_rate_2nd, grade_avg)
- Socio‑economic drivers (Tuition_fees_up_to_date, Scholarship_holder,
  Application_mode, Application_order)
- Filter by course (with readable course names)
- Data preview
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# Page config
st.set_page_config(
    page_title="Student Risk Dashboard",
    page_icon="🎓",
    layout="wide",
)

# ---------------------------------------------------------------------
# 1. THEME & STYLING (Dark mode)
# ---------------------------------------------------------------------
DARK_BG = "#0b0f14"
CARD_BG = "#11161f"
CARD_BORDER = "rgba(255,255,255,0.08)"
TEXT = "#f4f4f4"
MUTED = "#b4bcc9"
GRID = "#263041"
PALETTE = ["#488f31", "#bbba77", "#ffeeda", "#f0a281", "#de425b"]

st.markdown(
    f"""
    <style>
        .stApp {{
            background: {DARK_BG};
            color: {TEXT};
        }}
        div[data-testid="stMetric"] {{
            background: {CARD_BG};
            border: 1px solid {CARD_BORDER};
            border-radius: 16px;
            padding: 14px 16px;
        }}
        .card-block {{
            background: {CARD_BG};
            border: 1px solid {CARD_BORDER};
            border-radius: 18px;
            padding: 14px 16px;
            margin-bottom: 12px;
        }}
        .card-title {{
            font-size: 1.03rem;
            font-weight: 700;
            margin-bottom: 0.15rem;
        }}
        .card-subtitle {{
            color: {MUTED};
            margin-bottom: 0.65rem;
        }}
        .section-head {{
            margin-top: 0.25rem;
            margin-bottom: 0.15rem;
            font-size: 1.15rem;
            font-weight: 700;
        }}
        .section-desc {{
            color: {MUTED};
            margin-bottom: 0.65rem;
        }}
    </style>
    """,
    unsafe_allow_html=True,
)

# Plotly defaults
px.defaults.template = go.layout.Template(
    layout=go.Layout(
        paper_bgcolor=DARK_BG,
        plot_bgcolor=DARK_BG,
        font=dict(color=TEXT),
        xaxis=dict(gridcolor=GRID, zerolinecolor=GRID),
        yaxis=dict(gridcolor=GRID, zerolinecolor=GRID),
        legend=dict(bgcolor="rgba(0,0,0,0)"),
        colorway=PALETTE,
    )
)

# ---------------------------------------------------------------------
# 2. HELPER FUNCTIONS
# ---------------------------------------------------------------------
def canonical(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", str(name).strip().lower())

# Column mapping (needed to normalise raw CSV columns if we read original data)
RAW_TO_NOTEBOOK_COLS = {
    "Marital Status": "Marital_status",
    "Application mode": "Application_mode",
    "Application order": "Application_order",
    "Course": "Course",
    "Daytime/evening attendance": "Daytime_evening_attendance",
    "Previous qualification": "Previous_qualification",
    "Previous qualification (grade)": "Previous_qualification_grade",
    "Nacionality": "Nacionality",
    "Mother's qualification": "Mothers_qualification",
    "Father's qualification": "Fathers_qualification",
    "Mother's occupation": "Mothers_occupation",
    "Father's occupation": "Fathers_occupation",
    "Admission grade": "Admission_grade",
    "Displaced": "Displaced",
    "Educational special needs": "Educational_special_needs",
    "Debtor": "Debtor",
    "Tuition fees up to date": "Tuition_fees_up_to_date",
    "Gender": "Gender",
    "Scholarship holder": "Scholarship_holder",
    "Age at enrollment": "Age_at_enrollment",
    "International": "International",
    "Curricular units 1st sem (credited)": "Curricular_units_1st_sem_credited",
    "Curricular units 1st sem (enrolled)": "Curricular_units_1st_sem_enrolled",
    "Curricular units 1st sem (evaluations)": "Curricular_units_1st_sem_evaluations",
    "Curricular units 1st sem (approved)": "Curricular_units_1st_sem_approved",
    "Curricular units 1st sem (grade)": "Curricular_units_1st_sem_grade",
    "Curricular units 1st sem (without evaluations)": "Curricular_units_1st_sem_without_evaluations",
    "Curricular units 2nd sem (credited)": "Curricular_units_2nd_sem_credited",
    "Curricular units 2nd sem (enrolled)": "Curricular_units_2nd_sem_enrolled",
    "Curricular units 2nd sem (evaluations)": "Curricular_units_2nd_sem_evaluations",
    "Curricular units 2nd sem (approved)": "Curricular_units_2nd_sem_approved",
    "Curricular units 2nd sem (grade)": "Curricular_units_2nd_sem_grade",
    "Curricular units 2nd sem (without evaluations)": "Curricular_units_2nd_sem_without_evaluations",
    "Unemployment rate": "Unemployment_rate",
    "Inflation rate": "Inflation_rate",
    "GDP": "GDP",
    "Status": "Status",
}
CANONICAL_RAW_MAP = {canonical(k): v for k, v in RAW_TO_NOTEBOOK_COLS.items()}
NOTEBOOK_COLUMNS = set(RAW_TO_NOTEBOOK_COLS.values())

def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Rename columns to notebook names."""
    rename_map = {}
    for col in df.columns:
        key = canonical(col)
        if key in CANONICAL_RAW_MAP:
            rename_map[col] = CANONICAL_RAW_MAP[key]
        elif col in NOTEBOOK_COLUMNS:
            rename_map[col] = col
    return df.rename(columns=rename_map).copy()

def get_risk_level(prob_graduate: float) -> str:
    if prob_graduate >= 0.7:
        return "Low risk"      # Actually low risk of dropout
    elif prob_graduate >= 0.3:
        return "Medium risk"
    else:
        return "High risk"

# Course mapping (from provided list)
COURSE_MAP = {
    33: "Biofuel Production Technologies",
    171: "Animation and Multimedia Design",
    8014: "Social Service (evening attendance)",
    9003: "Agronomy",
    9070: "Communication Design",
    9085: "Veterinary Nursing",
    9119: "Informatics Engineering",
    9130: "Equinculture",
    9147: "Management",
    9238: "Social Service",
    9254: "Tourism",
    9500: "Nursing",
    9556: "Oral Hygiene",
    9670: "Advertising and Marketing Management",
    9773: "Journalism and Communication",
    9853: "Basic Education",
    9991: "Management (evening attendance)",
}

def map_course(code):
    """Convert numeric course code to human‑readable name."""
    try:
        return COURSE_MAP.get(int(code), f"Course {code}")
    except:
        return code

# ---------------------------------------------------------------------
# 3. LOAD DATA
# ---------------------------------------------------------------------
@st.cache_data
def load_pred_data(path: str = "pred_data.csv") -> pd.DataFrame:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"File not found: {p.resolve()}")
    df = pd.read_csv(p)
    df = normalize_columns(df)
    # Ensure we have Original_Status (the true status from input)
    if "Original_Status" not in df.columns and "Status" in df.columns:
        df["Original_Status"] = df["Status"]
    # Add risk level for enrolled students
    if "Prob_Graduate" in df.columns:
        mask = df["Original_Status"].astype(str).str.strip() == "Enrolled"
        df["Risk_Level"] = ""
        df.loc[mask, "Risk_Level"] = df.loc[mask, "Prob_Graduate"].apply(get_risk_level)
    # Map Course codes to readable names
    if "Course" in df.columns:
        df["Course_Name"] = df["Course"].apply(map_course)
    return df

try:
    df = load_pred_data("pred_data.csv")
except Exception as e:
    st.error(f"Error loading data: {e}")
    st.info("Please run the prediction app first to generate pred_data.csv.")
    st.stop()

# ---------------------------------------------------------------------
# 4. FILTER ENROLLED STUDENTS
# ---------------------------------------------------------------------
if "Original_Status" not in df.columns:
    st.error("Column 'Original_Status' not found. Cannot identify enrolled students.")
    st.stop()

enrolled = df[df["Original_Status"].astype(str).str.strip() == "Enrolled"].copy()
if len(enrolled) == 0:
    st.warning("No enrolled students found in the dataset.")
    st.stop()

# ---------------------------------------------------------------------
# 5. EXECUTIVE SUMMARY (First row)
# ---------------------------------------------------------------------
st.title("Student Risk Dashboard")
st.markdown("### Goal: Predict graduation probability for enrolled students")

# First row: KPIs
col1, col2, col3, col4 = st.columns(4)
with col1:
    total_students = len(df)
    st.metric("Total Students", f"{total_students:,}")
with col2:
    grad_count = (df["Original_Status"].astype(str).str.strip() == "Graduate").sum()
    st.metric("Graduate (actual)", f"{grad_count:,}")
with col3:
    dropout_count = (df["Original_Status"].astype(str).str.strip() == "Dropout").sum()
    st.metric("Dropout (actual)", f"{dropout_count:,}")
with col4:
    enrolled_count = len(enrolled)
    st.metric("Enrolled (actual)", f"{enrolled_count:,}")

st.markdown("---")

# ---------------------------------------------------------------------
# 6. PREDICTION SUMMARY & RISK DISTRIBUTION (Second row)
# ---------------------------------------------------------------------
col_left, col_right = st.columns(2)

with col_left:
    st.markdown("### Prediction Summary (Enrolled)")
    predicted_graduate = (enrolled["Prob_Graduate"] > 0.5).sum()
    predicted_dropout = (enrolled["Prob_Graduate"] <= 0.5).sum()
    avg_prob = enrolled["Prob_Graduate"].mean()

    st.metric("Predicted Graduate (>50%)", f"{predicted_graduate:,}")
    st.metric("Predicted Dropout (≤50%)", f"{predicted_dropout:,}")

    # Progress bar for average probability
    st.markdown("**Average Graduation Probability**")
    st.progress(avg_prob, text=f"{avg_prob:.1%}")

with col_right:
    st.markdown("### Risk Distribution")
    risk_counts = enrolled["Risk_Level"].value_counts().reset_index()
    risk_counts.columns = ["Risk Level", "Count"]
    # Ensure consistent order: High, Medium, Low
    risk_counts["Risk Level"] = pd.Categorical(
        risk_counts["Risk Level"], categories=["High risk", "Medium risk", "Low risk"], ordered=True
    )
    risk_counts = risk_counts.sort_values("Risk Level")
    fig_pie = px.pie(
        risk_counts,
        values="Count",
        names="Risk Level",
        color="Risk Level",
        color_discrete_map={"High risk": "#de425b", "Medium risk": "#ffeeda", "Low risk": "#488f31"},
        title="Risk Level (Enrolled Students)",
        hole=0.4,
    )
    fig_pie.update_traces(textposition="inside", textinfo="percent+label")
    fig_pie.update_layout(height=400)
    st.plotly_chart(fig_pie, use_container_width=True)

st.markdown("---")

# ---------------------------------------------------------------------
# 7. DRIVER CHARTS (using model feature importances)
# ---------------------------------------------------------------------
@st.cache_resource
def load_feature_importance():
    model_path = Path("model/best_model.pkl")
    feature_path = Path("model/feature_names.pkl")
    if not model_path.exists() or not feature_path.exists():
        return None, {}
    model = joblib.load(model_path)
    feature_names = joblib.load(feature_path)
    importances = model.feature_importances_
    df_imp = pd.DataFrame({"Feature": feature_names, "Importance": importances}).sort_values("Importance", ascending=False)
    return df_imp, {}

fi_df, _ = load_feature_importance()

if fi_df is not None:
    # Academic drivers: the five derived features
    academic_features = [
        "approval_rate_1st",
        "failure_rate_1st",
        "approval_rate_2nd",
        "failure_rate_2nd",
        "grade_avg",
    ]
    academic_imp = fi_df[fi_df["Feature"].isin(academic_features)].copy()
    if len(academic_imp) > 0:
        academic_imp = academic_imp.sort_values("Importance", ascending=False)
        fig_academic = px.bar(
            academic_imp,
            x="Importance",
            y="Feature",
            orientation="h",
            color="Importance",
            color_continuous_scale=[(0.0, PALETTE[0]), (0.5, PALETTE[2]), (1.0, PALETTE[4])],
            title="Academic Driver (Feature Importance)",
        )
        fig_academic.update_layout(height=400)
    else:
        fig_academic = go.Figure()
        fig_academic.add_annotation(text="Academic features not found in model", x=0.5, y=0.5, showarrow=False)

    # Socio-economic drivers
    socio_features = [
        "Tuition_fees_up_to_date",
        "Scholarship_holder",
        "Application_mode",
        "Application_order",
    ]
    socio_imp = fi_df[fi_df["Feature"].isin(socio_features)].copy()
    if len(socio_imp) > 0:
        socio_imp = socio_imp.sort_values("Importance", ascending=False)
        fig_socio = px.bar(
            socio_imp,
            x="Importance",
            y="Feature",
            orientation="h",
            color="Importance",
            color_continuous_scale=[(0.0, PALETTE[0]), (0.5, PALETTE[2]), (1.0, PALETTE[4])],
            title="Socio‑Economic Driver (Feature Importance)",
        )
        fig_socio.update_layout(height=400)
    else:
        fig_socio = go.Figure()
        fig_socio.add_annotation(text="Socio‑economic features not found in model", x=0.5, y=0.5, showarrow=False)

    # Third row: two columns for driver charts
    col_acad, col_socio = st.columns(2)
    with col_acad:
        st.plotly_chart(fig_academic, use_container_width=True)
    with col_socio:
        st.plotly_chart(fig_socio, use_container_width=True)
else:
    st.warning("Feature importance not available (best_model.pkl or feature_names.pkl missing).")

st.markdown("---")

# ---------------------------------------------------------------------
# 8. ADDITIONAL: Filter by course and data table
# ---------------------------------------------------------------------
st.subheader("Filter by Course (Enrolled Students)")
if "Course_Name" in enrolled.columns:
    courses = ["All"] + sorted(enrolled["Course_Name"].dropna().unique())
    selected_course = st.selectbox("Select Course", courses)
    if selected_course != "All":
        filtered = enrolled[enrolled["Course_Name"] == selected_course]
        st.write(f"Showing {len(filtered)} students from course {selected_course}")
        col_f1, col_f2, col_f3 = st.columns(3)
        col_f1.metric("Count", len(filtered))
        col_f2.metric("Avg Graduation Probability", f"{filtered['Prob_Graduate'].mean():.2%}")
        col_f3.metric("High Risk (%)", f"{(filtered['Prob_Graduate'] < 0.3).mean():.1%}")
        fig_filt = px.histogram(filtered, x="Prob_Graduate", nbins=15, title="Probability Distribution (Filtered)")
        st.plotly_chart(fig_filt, use_container_width=True)

# Data table preview
st.subheader("Enrolled Student Data (First 100 rows)")
preview_cols = [
    "Original_Status",
    "Predicted_Status",
    "Prob_Graduate",
    "Risk_Level",
    "Course_Name",
    "Gender",
    "Age_at_enrollment",
    "Admission_grade",
    "approval_rate_1st",
    "failure_rate_1st",
    "approval_rate_2nd",
    "failure_rate_2nd",
    "grade_avg",
]
available_cols = [c for c in preview_cols if c in enrolled.columns]
st.dataframe(enrolled[available_cols].head(100), use_container_width=True)

st.markdown("---")
st.caption("Model predictions are based on a Random Forest classifier trained on historical student data.")