# dashboard.py - Student Risk Dashboard
# ---------------------------------------------------------------------
# This dashboard loads the predictions generated by app.py, filters
# currently enrolled students, and shows key metrics, risk distribution,
# and driver charts based on model feature importance.
# Additionally, it includes comprehensive multivariate visualizations
# comparing dropout vs graduate across key features.
# ---------------------------------------------------------------------

from __future__ import annotations

import re
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Page config
st.set_page_config(
    page_title="Student Risk Dashboard",
    page_icon="🎓",
    layout="wide",
)

# ---------------------------------------------------------------------
# 1. Theme & styling (dark mode)
# ---------------------------------------------------------------------
DARK_BG = "#0b0f14"
CARD_BG = "#11161f"
CARD_BORDER = "rgba(255,255,255,0.08)"
TEXT = "#f4f4f4"
MUTED = "#b4bcc9"
GRID = "#263041"
PALETTE = ["#488f31", "#bbba77", "#ffeeda", "#f0a281", "#de425b"]

st.markdown(
    f"""
    <style>
        .stApp {{
            background: {DARK_BG};
            color: {TEXT};
        }}
        div[data-testid="stMetric"] {{
            background: {CARD_BG};
            border: 1px solid {CARD_BORDER};
            border-radius: 16px;
            padding: 14px 16px;
        }}
        .card-block {{
            background: {CARD_BG};
            border: 1px solid {CARD_BORDER};
            border-radius: 18px;
            padding: 14px 16px;
            margin-bottom: 12px;
        }}
        .card-title {{
            font-size: 1.03rem;
            font-weight: 700;
            margin-bottom: 0.15rem;
        }}
        .card-subtitle {{
            color: {MUTED};
            margin-bottom: 0.65rem;
        }}
        .section-head {{
            margin-top: 0.25rem;
            margin-bottom: 0.15rem;
            font-size: 1.15rem;
            font-weight: 700;
        }}
        .section-desc {{
            color: {MUTED};
            margin-bottom: 0.65rem;
        }}
    </style>
    """,
    unsafe_allow_html=True,
)

# Plotly defaults
px.defaults.template = go.layout.Template(
    layout=go.Layout(
        paper_bgcolor=DARK_BG,
        plot_bgcolor=DARK_BG,
        font=dict(color=TEXT),
        xaxis=dict(gridcolor=GRID, zerolinecolor=GRID),
        yaxis=dict(gridcolor=GRID, zerolinecolor=GRID),
        legend=dict(bgcolor="rgba(0,0,0,0)"),
        colorway=PALETTE,
    )
)

# ---------------------------------------------------------------------
# 2. Helper functions
# ---------------------------------------------------------------------
def canonical(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", str(name).strip().lower())

# Column mapping (same as in app.py)
RAW_TO_NOTEBOOK_COLS = {
    "Marital Status": "Marital_status",
    "Application mode": "Application_mode",
    "Application order": "Application_order",
    "Course": "Course",
    "Daytime/evening attendance": "Daytime_evening_attendance",
    "Previous qualification": "Previous_qualification",
    "Previous qualification (grade)": "Previous_qualification_grade",
    "Nacionality": "Nacionality",
    "Mother's qualification": "Mothers_qualification",
    "Father's qualification": "Fathers_qualification",
    "Mother's occupation": "Mothers_occupation",
    "Father's occupation": "Fathers_occupation",
    "Admission grade": "Admission_grade",
    "Displaced": "Displaced",
    "Educational special needs": "Educational_special_needs",
    "Debtor": "Debtor",
    "Tuition fees up to date": "Tuition_fees_up_to_date",
    "Gender": "Gender",
    "Scholarship holder": "Scholarship_holder",
    "Age at enrollment": "Age_at_enrollment",
    "International": "International",
    "Curricular units 1st sem (credited)": "Curricular_units_1st_sem_credited",
    "Curricular units 1st sem (enrolled)": "Curricular_units_1st_sem_enrolled",
    "Curricular units 1st sem (evaluations)": "Curricular_units_1st_sem_evaluations",
    "Curricular units 1st sem (approved)": "Curricular_units_1st_sem_approved",
    "Curricular units 1st sem (grade)": "Curricular_units_1st_sem_grade",
    "Curricular units 1st sem (without evaluations)": "Curricular_units_1st_sem_without_evaluations",
    "Curricular units 2nd sem (credited)": "Curricular_units_2nd_sem_credited",
    "Curricular units 2nd sem (enrolled)": "Curricular_units_2nd_sem_enrolled",
    "Curricular units 2nd sem (evaluations)": "Curricular_units_2nd_sem_evaluations",
    "Curricular units 2nd sem (approved)": "Curricular_units_2nd_sem_approved",
    "Curricular units 2nd sem (grade)": "Curricular_units_2nd_sem_grade",
    "Curricular units 2nd sem (without evaluations)": "Curricular_units_2nd_sem_without_evaluations",
    "Unemployment rate": "Unemployment_rate",
    "Inflation rate": "Inflation_rate",
    "GDP": "GDP",
    "Status": "Status",
}
CANONICAL_RAW_MAP = {canonical(k): v for k, v in RAW_TO_NOTEBOOK_COLS.items()}
NOTEBOOK_COLUMNS = set(RAW_TO_NOTEBOOK_COLS.values())

def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Rename columns to notebook names."""
    rename_map = {}
    for col in df.columns:
        key = canonical(col)
        if key in CANONICAL_RAW_MAP:
            rename_map[col] = CANONICAL_RAW_MAP[key]
        elif col in NOTEBOOK_COLUMNS:
            rename_map[col] = col
    return df.rename(columns=rename_map).copy()

def get_risk_level(prob_graduate: float) -> str:
    """Risk level based on graduation probability."""
    if prob_graduate >= 0.7:
        return "Low risk"      # low risk of dropout
    elif prob_graduate >= 0.3:
        return "Medium risk"
    else:
        return "High risk"

# Course mapping (from notebook)
COURSE_MAP = {
    33: "Biofuel Production Technologies",
    171: "Animation and Multimedia Design",
    8014: "Social Service (evening attendance)",
    9003: "Agronomy",
    9070: "Communication Design",
    9085: "Veterinary Nursing",
    9119: "Informatics Engineering",
    9130: "Equinculture",
    9147: "Management",
    9238: "Social Service",
    9254: "Tourism",
    9500: "Nursing",
    9556: "Oral Hygiene",
    9670: "Advertising and Marketing Management",
    9773: "Journalism and Communication",
    9853: "Basic Education",
    9991: "Management (evening attendance)",
}

def map_course(code):
    try:
        return COURSE_MAP.get(int(code), f"Course {code}")
    except:
        return code

# ---------------------------------------------------------------------
# 3. Load prediction data
# ---------------------------------------------------------------------
@st.cache_data
def load_pred_data(path: str = "pred_data.csv") -> pd.DataFrame:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"File not found: {p.resolve()}")
    df = pd.read_csv(p)
    df = normalize_columns(df)
    # Ensure Original_Status column exists
    if "Original_Status" not in df.columns and "Status" in df.columns:
        df["Original_Status"] = df["Status"]
    # Add risk level for enrolled students
    if "Prob_Graduate" in df.columns:
        mask = df["Original_Status"].astype(str).str.strip() == "Enrolled"
        df["Risk_Level"] = ""
        df.loc[mask, "Risk_Level"] = df.loc[mask, "Prob_Graduate"].apply(get_risk_level)
    # Map Course codes to readable names
    if "Course" in df.columns:
        df["Course_Name"] = df["Course"].apply(map_course)
    return df

try:
    df = load_pred_data("pred_data.csv")
except Exception as e:
    st.error(f"Error loading data: {e}")
    st.info("Please run the prediction app first to generate pred_data.csv.")
    st.stop()

# ---------------------------------------------------------------------
# 4. Filter data for analysis (only Dropout and Graduate)
# ---------------------------------------------------------------------
if "Original_Status" not in df.columns:
    st.error("Column 'Original_Status' not found. Cannot identify student status.")
    st.stop()

# Create a column for analysis: we'll use "Actual_Status" (Dropout or Graduate)
df_analysis = df[df["Original_Status"].astype(str).str.strip().isin(["Dropout", "Graduate"])].copy()
if len(df_analysis) == 0:
    st.warning("No students with actual Dropout/Graduate status found in the dataset.")
    st.stop()

# ---------------------------------------------------------------------
# 5. Executive summary (KPIs)
# ---------------------------------------------------------------------
st.title("Student Risk Dashboard")
st.markdown("### Analysis of Dropout vs Graduate Students")

col1, col2, col3 = st.columns(3)
with col1:
    total_students = len(df_analysis)
    st.metric("Total Students (Dropout + Graduate)", f"{total_students:,}")
with col2:
    grad_count = (df_analysis["Original_Status"].astype(str).str.strip() == "Graduate").sum()
    st.metric("Graduate", f"{grad_count:,}")
with col3:
    dropout_count = (df_analysis["Original_Status"].astype(str).str.strip() == "Dropout").sum()
    st.metric("Dropout", f"{dropout_count:,}")

st.markdown("---")


# ---------------------------------------------------------------------
# 5.5. Prediction summary & risk distribution (based on dropout probability)
# ---------------------------------------------------------------------

# Filter enrolled students
enrolled = df[df["Original_Status"].astype(str).str.strip() == "Enrolled"].copy()

if len(enrolled) == 0:
    st.warning("No enrolled students found in the dataset.")
else:
    col_left, col_right = st.columns(2)

    with col_left:
        st.markdown("### Predicted Dropout Risk (Enrolled Students)")

        # Define risk categories based on dropout probability (0=Graduate, 1=Dropout)
        high_risk = (enrolled["Prob_Dropout"] > 0.7).sum()
        medium_risk = ((enrolled["Prob_Dropout"] > 0.3) & (enrolled["Prob_Dropout"] <= 0.7)).sum()
        low_risk = (enrolled["Prob_Dropout"] <= 0.3).sum()
        total_enrolled = len(enrolled)

        # Display metrics
        st.metric("Total Enrolled", f"{total_enrolled:,}")
        st.metric("High Risk (Dropout >70%)", f"{high_risk:,}")
        st.metric("Medium Risk (30%–70%)", f"{medium_risk:,}")
        st.metric("Low Risk (Dropout ≤30%)", f"{low_risk:,}")

    with col_right:
        st.markdown("### Risk Distribution")
        # Prepare data for pie chart
        risk_counts = pd.DataFrame({
            "Risk Level": ["High risk", "Medium risk", "Low risk"],
            "Count": [high_risk, medium_risk, low_risk]
        })
        # Filter out zero-count categories if needed
        risk_counts = risk_counts[risk_counts["Count"] > 0]

        fig_pie = px.pie(
            risk_counts,
            values="Count",
            names="Risk Level",
            color="Risk Level",
            color_discrete_map={
                "High risk": "#de425b",
                "Medium risk": "#ffeeda",
                "Low risk": "#488f31"
            },
            title="Dropout Risk Level (Enrolled Students)",
            hole=0.4,
        )
        fig_pie.update_traces(textposition="inside", textinfo="percent+label")
        fig_pie.update_layout(height=400)
        st.plotly_chart(fig_pie, use_container_width=True)

    st.markdown("---")


# ---------------------------------------------------------------------
# 6. Multivariate visualizations: categorical features
# ---------------------------------------------------------------------
st.subheader("Categorical Features vs Student Status")
st.markdown("Comparison of dropout vs graduate across key categorical attributes.")

# Define categorical columns of interest
categorical_cols = [
    "Marital_status", "Gender", "Debtor", "Scholarship_holder", 
    "Tuition_fees_up_to_date", "Displaced", "Educational_special_needs"
]
# Add Course_Name if available
if "Course_Name" in df_analysis.columns:
    categorical_cols.append("Course_Name")

# Prepare plots
categorical_plots = []
for col in categorical_cols:
    if col in df_analysis.columns:
        # Count occurrences per category and status
        counts = df_analysis.groupby([col, "Original_Status"]).size().reset_index(name="Count")
        # Clean up values for better readability
        if col == "Marital_status":
            counts[col] = counts[col].map({1: "Single", 2: "Married", 3: "Divorced", 4: "Widowed"})
        if col == "Gender":
            counts[col] = counts[col].map({1: "Male", 0: "Female"})
        if col == "Debtor":
            counts[col] = counts[col].map({1: "Yes", 0: "No"})
        if col == "Scholarship_holder":
            counts[col] = counts[col].map({1: "Yes", 0: "No"})
        if col == "Tuition_fees_up_to_date":
            counts[col] = counts[col].map({1: "Yes", 0: "No"})
        if col == "Displaced":
            counts[col] = counts[col].map({1: "Yes", 0: "No"})
        if col == "Educational_special_needs":
            counts[col] = counts[col].map({1: "Yes", 0: "No"})
        # Create bar chart
        fig = px.bar(
            counts,
            x=col,
            y="Count",
            color="Original_Status",
            barmode="group",
            title=f"Status by {col.replace('_', ' ')}",
            labels={col: col.replace('_', ' '), "Count": "Number of Students"},
            color_discrete_map={"Dropout": PALETTE[4], "Graduate": PALETTE[0]}
        )
        fig.update_layout(xaxis_tickangle=-45 if len(counts[col].unique()) > 5 else 0)
        categorical_plots.append(fig)

# Display categorical plots in rows of 3
for i in range(0, len(categorical_plots), 3):
    cols = st.columns(3)
    for j in range(3):
        if i + j < len(categorical_plots):
            with cols[j]:
                st.plotly_chart(categorical_plots[i + j], use_container_width=True)

# ---------------------------------------------------------------------
# 7. Multivariate visualizations: numerical features
# ---------------------------------------------------------------------
st.subheader("Numerical Features vs Student Status")
st.markdown("Distribution comparison for continuous features.")

# Define numerical columns of interest
numerical_cols = [
    "Age_at_enrollment", "Admission_grade", 
    "Curricular_units_1st_sem_evaluations", "Curricular_units_1st_sem_grade",
    "Curricular_units_2nd_sem_evaluations", "Curricular_units_2nd_sem_grade",
    "Unemployment_rate", "Inflation_rate", "GDP"
]
# Add derived features if present
for col in ["approval_rate_1st", "failure_rate_1st", "approval_rate_2nd", "failure_rate_2nd", "grade_avg"]:
    if col in df_analysis.columns:
        numerical_cols.append(col)

# Create box plots
box_plots = []
for col in numerical_cols:
    if col in df_analysis.columns:
        fig = px.box(
            df_analysis,
            x="Original_Status",
            y=col,
            color="Original_Status",
            title=f"{col.replace('_', ' ')}",
            labels={col: col.replace('_', ' '), "Original_Status": "Status"},
            color_discrete_map={"Dropout": PALETTE[4], "Graduate": PALETTE[0]}
        )
        fig.update_layout(showlegend=False)
        box_plots.append(fig)

# Display box plots in rows of 3
st.write("**Box plots**")
for i in range(0, len(box_plots), 3):
    cols = st.columns(3)
    for j in range(3):
        if i + j < len(box_plots):
            with cols[j]:
                st.plotly_chart(box_plots[i + j], use_container_width=True)

# Histograms
st.write("**Histograms**")
hist_plots = []
for col in numerical_cols:
    if col in df_analysis.columns:
        fig = px.histogram(
            df_analysis,
            x=col,
            color="Original_Status",
            barmode="overlay",
            opacity=0.6,
            title=f"{col.replace('_', ' ')}",
            color_discrete_map={"Dropout": PALETTE[4], "Graduate": PALETTE[0]}
        )
        hist_plots.append(fig)

for i in range(0, len(hist_plots), 3):
    cols = st.columns(3)
    for j in range(3):
        if i + j < len(hist_plots):
            with cols[j]:
                st.plotly_chart(hist_plots[i + j], use_container_width=True)

# ---------------------------------------------------------------------
# 8. Scatter plot for multivariate interaction
# ---------------------------------------------------------------------
st.subheader("Feature Interactions")
st.markdown("Scatter plot showing relationship between two numerical features, colored by status.")

# Choose two features that are likely important
feature_x = st.selectbox("Select X-axis feature", numerical_cols, index=0)
feature_y = st.selectbox("Select Y-axis feature", numerical_cols, index=min(1, len(numerical_cols)-1))

fig_scatter = px.scatter(
    df_analysis,
    x=feature_x,
    y=feature_y,
    color="Original_Status",
    title=f"{feature_x.replace('_', ' ')} vs {feature_y.replace('_', ' ')}",
    labels={feature_x: feature_x.replace('_', ' '), feature_y: feature_y.replace('_', ' ')},
    color_discrete_map={"Dropout": PALETTE[4], "Graduate": PALETTE[0]},
    opacity=0.6,
)
st.plotly_chart(fig_scatter, use_container_width=True)

# ---------------------------------------------------------------------
# 9. Feature importance (if available)
# ---------------------------------------------------------------------
@st.cache_resource
def load_feature_importance():
    model_path = Path("model/best_model.pkl")
    feature_path = Path("model/feature_names.pkl")
    if not model_path.exists() or not feature_path.exists():
        return None, None
    model = joblib.load(model_path)
    feature_names = joblib.load(feature_path)
    importances = model.feature_importances_
    df_imp = pd.DataFrame({"Feature": feature_names, "Importance": importances}).sort_values("Importance", ascending=False)
    return df_imp, feature_names

fi_df, _ = load_feature_importance()

if fi_df is not None:
    st.subheader("Model Feature Importance")
    fig_fi = px.bar(
        fi_df.head(15),
        x="Importance",
        y="Feature",
        orientation="h",
        title="Top 15 Most Important Features (Random Forest)",
        color="Importance",
        color_continuous_scale=[(0.0, PALETTE[0]), (0.5, PALETTE[2]), (1.0, PALETTE[4])],
    )
    fig_fi.update_layout(height=600)
    st.plotly_chart(fig_fi, use_container_width=True)
else:
    st.warning("Feature importance not available (best_model.pkl or feature_names.pkl missing).")

# ---------------------------------------------------------------------
# 10. Filter by course and data preview (optional)
# ---------------------------------------------------------------------
st.subheader("Filter by Course (Analysis Data)")
if "Course_Name" in df_analysis.columns:
    courses = ["All"] + sorted(df_analysis["Course_Name"].dropna().unique())
    selected_course = st.selectbox("Select Course", courses)
    if selected_course != "All":
        filtered = df_analysis[df_analysis["Course_Name"] == selected_course]
        st.write(f"Showing {len(filtered)} students from course {selected_course}")
        col_f1, col_f2, col_f3 = st.columns(3)
        col_f1.metric("Count", len(filtered))
        col_f2.metric("Graduate Rate", f"{(filtered['Original_Status'] == 'Graduate').mean():.1%}")
        col_f3.metric("Dropout Rate", f"{(filtered['Original_Status'] == 'Dropout').mean():.1%}")

st.subheader("Data Preview")
preview_cols = [
    "Original_Status",
    "Predicted_Status",
    "Prob_Graduate",
    "Risk_Level",
    "Course_Name",
    "Gender",
    "Age_at_enrollment",
    "Admission_grade",
    "approval_rate_1st",
    "failure_rate_1st",
    "grade_avg",
]
available_cols = [c for c in preview_cols if c in df_analysis.columns]
st.dataframe(df_analysis[available_cols].head(100), use_container_width=True)

st.markdown("---")
st.caption("Model predictions are based on a Random Forest classifier trained on historical student data.")